#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Tue Sep 29 04:58:07 ART 2026
farmersdelight=true
mcwbridges=true
mcwstairs=true
decorative_blocks=true
handcrafted=true
mcwroofs=true
another_furniture=true
mcwdoors=true
mcwfences=true
mcwtrpdoors=true
mcwfurnitures=true
hearth_and_home=true
mcwwindows=true
create=true
mcwpaths=true
mcwlights=true
