#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 25 07:07:01 ART 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=ComplementaryUnbound_r5.2.1.zip
enableShaders=true
